### ISSUE TITLE
Incorrect instructions for selecting drives in creating disk pool

### ISSUE THREAD

**Issue by alonsod-netapp** [NetAppDocs/e-series-cli#10]
Page: [Create disk pool](https://docs.netapp.com/us-en/e-series-cli/commands-a-z/create-diskpool.html)

The instructions for the "drives" parameter say to "Enclose the tray ID value, the drawer ID value, and the slot ID value in square brackets ([ ])."

When I tried this on a system running latest SANtricity OS, I got an error about encountering "[" instead of an integer.  When I tried the command without enclosing the tray ID, drawer ID and slot ID of the drives in square brackets, the command ran successfully.

The statement to enclose drive IDs in square brackets should be removed.

Also, in the second paragraph of "drives" parameter's second paragraph under "Description", it states " Drive trays compatible with E2800 and E5700 controllers have slot ID numbers starting at 0."  This statement should also include EF300 and EF600, those shelves start with "0" as well.

**Comment by netapp-driley** [comment]
Hi Alonso,

I'll take a look at this and updated the topic as needed. I'll keep you posted once the changes are available.  

If you need anything else, please let me know.

Thanks,

Don

**Comment by netapp-driley** [comment]
This correction will be available with the publication of the latest E-Series release documentation.
