### ISSUE TITLE
Thin volume syntax found twice with no difference

### ISSUE THREAD

**Issue by netapp-bserrano** [NetAppDocs/e-series-cli#11]
Page: [Create volume in disk pool](https://docs.netapp.com/us-en/e-series-cli/commands-a-z/create-volume-diskpool.html)

**Comment by netapp-driley** [comment]
Hi bserrano,

I'll take a look at this and updated the topic as needed. I'll keep you posted once the changes are available.

If you need anything else, please let me know.

Thanks,

Don

**Comment by netapp-driley** [comment]
This correction will be available with the publication of the latest E-Series release documentation.
