### ISSUE TITLE
Thin provisioning not supported on EF300 and EF600

### ISSUE THREAD

**Issue by alonsod-netapp** [NetAppDocs/e-series-cli#12]
Page: [Create volume in disk pool](https://docs.netapp.com/us-en/e-series-cli/commands-a-z/create-volume-diskpool.html)

Please add a note that thin provisioned volumes are not supported on EF300 or EF600.

**Comment by netapp-martyh** [comment]
Thank you for your feedback. We will reviewing and make updates as needed.

**Comment by netapp-driley** [comment]
This item will be available in the next published release of the documentation.
