### ISSUE TITLE
Document edit request for Create RAID volume

### ISSUE THREAD

**Issue by Limahlm** [NetAppDocs/e-series-cli#2]
Page: [Create RAID volume (free extent based select)](https://docs.netapp.com/us-en/e-series-cli/commands-a-z/create-raid-volume-free-extent-based-select.html)

The customer encountered this issue (case: 2009265374)

While manually creating a Volume with Blocksize 512, this action fails: 

$ sudo SMcli -n ksrmraid01 -p [password] -c 'create volume volumeGroup=Krosy_ZFS capacity=1GB userLabel="test_kogeb_512b" blockSize=512;'
Performing syntax check...

Encountered "blockSize" at line 1, column 92.
Was expecting one of:
    "mapping" ...
    "cacheReadPrefetch" ...
    "capacity" ...
    "drawerLossProtect" ...
    "driveMediaType" ...
    "driveType" ...
    "dssPreAllocate" ...
    "freeCapacityArea" ...
    "owner" ...
    "dataAssurance" ...
    "RAIDLevel" ...
    "readAheadMultiplier" ...
    "secureDrives" ...
    "securityType" ...
    "segmentSize" ...
    "trayLossProtect" ...
    "usageHint" ...
    "userLabel" ...
    "volumeGroupUserLabel" ...
    ";" ...

SMcli failed.

Block size parameter is missing when the customer uses http but the parameter is available when https is used. 

Customer Request: 
Why is this information not documented in the Volume create page? 

The customer would like SMcli https mode information to be added to the Create RAID volume page and the additional parameters which are included.

**Comment by netapp-driley** [comment]
Hi @Limahlm - In order to better troubleshoot this issue, do you know what version of the CLI the customer is using?

**Comment by netapp-driley** [comment]
Blocksize parameter text added to Create Volume commands in the SMcli documentation. Changes will be available in the next published version of the documentation.
