### ISSUE TITLE
Max capacity of thin volume

### ISSUE THREAD

**Issue by naotocurry** [NetAppDocs/e-series-cli#20]
### Page URL

https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-thin-volume-attributes.html

### Page title

https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-thin-volume-attributes.html

### Summary

According to https://www.netapp.com/media/12421-tr4652.pdf, max capacity of thin volume seems to be 256TiB as follows in p23.
"The maximum thin-provisioned volume size is 256 TiB."

However, it is described 64TiB in https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-thin-volume-attributes.html. If 256TiB is correct max capacity, please fix the description in this page. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Updated the maximum virtual and physical capacity limits and published the revised document.
