### ISSUE TITLE
NTP security options do not work (not supported)

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/e-series-cli#23]
### Page URL

https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-controller-ntpservers.html

### Page title

Set controller NTP settings

### Summary

A customer was trying to configure NTP server on their controllers using security parameters included in the CLI help menu and doc. However, it did not work because E-Series does not support NTP secure.

The documentation needs to remove the NTP secure options. Confirmed with Dev that they are not supported in any GA release.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Hello, 

I worked with the E-Series developer to make the appropriate changes to the documentation for this issue. The changes for this topic will be published in the next revision release. 

If you have any other feedback, please let me know. 

Thanks again, 

Don Riley
