### ISSUE TITLE
Host channel value limits are incorrect

### ISSUE THREAD

**Issue by mcwhiteside** [NetAppDocs/e-series-cli#25]
### Page URL

https://docs.netapp.com/us-en/e-series-cli/commands-a-z/start-ioclog.html

### Page title

Start input output controller (IOC) dump

### Summary

This page says the host port channels are limited between 1-4. This is incorrect. Host port channels are limited between 1-8, since EF600 platforms support dual 4-port iSCSI HICs.
The following page is populated with accurate information for reference: https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-hostchannel.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-driley** [comment]
Thank you so much for your feedback. We'll get this updated in the documentation and keep you posted once the latest changes are available. 

Thank you, 

Don Riley

**Comment by netapp-driley** [comment]
This issue has been resolved.
