### ISSUE TITLE
Command should be deprecated 

### ISSUE THREAD

**Issue by jknauff** [NetAppDocs/e-series-cli#3]
Page: [Change SSD cache application type](https://docs.netapp.com/us-en/e-series-cli/commands-a-z/change-ssd-cache-application-type.html)

The functionality this command changed is no longer in use. The command does not change anything at the array level, but also doesn't error out to indicate nothing changed. Request removal of this command from the help documents. 
Thanks,
Jason Knauff

**Comment by netapp-jsnyder** [comment]
@jknauff Thanks. We will remove this command.

**Comment by netapp-driley** [comment]
Hi Jason - Thank you so much for your feedback. We will remove this command from the publication. Also, we're planning to do a review of the existing commands in the publication to make sure the command listings are up to date. This project will be ongoing and we'll keep you posted on the project. 

If you have any other comments or suggestions, please let us know. 

Thanks, 

Don Riley

**Comment by netapp-driley** [comment]
Per the originator's request on 12/12/2002, the request to deprecate the command is no longer needed (see below)
![image](https://user-images.githubusercontent.com/18422994/217587943-53628e43-0abe-4e7a-9108-ef34f9ba0a9b.png)
