### ISSUE TITLE
Volume Group status examples are incorrect

### ISSUE THREAD

**Issue by swagner49** [NetAppDocs/e-series-cli#9]
Page: [Show volume group](https://docs.netapp.com/us-en/e-series-cli/commands-a-z/show-volumegroup.html)

This command returns this information about a volume group:
 - The status (Online or Offline)

There is no online/offline status for volume groups.  Possible status values in the current user interface are 
{Optimal, Degraded, Failed, Missing, Forced - ready for import, Contingent - preparing for import, Exported - ready for import}

Fujitsu asked about this, as they (correctly) believe there is no Online or Offline status for volume groups.
I would recommend listing Optimal, Degraded, Failed, and possiby Missing.  The other three are very uncommon, and would apply only to special situations,

**Comment by netapp-driley** [comment]
Hi Steve, 

I assigned these users stories to myself, and I’ll get started on making the changes. These changes should be available in our next release. 

If you need anything else, please let me know. 

Thanks, 

Don

**Comment by netapp-driley** [comment]
This correction will be available with the publication of the latest E-Series release documentation.
